/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

/**
 *
 * @author rusla
 */
public class adminmenu2 extends javax.swing.JFrame {

    /**
     * Creates new form adminmenu2
     */
    public adminmenu2() {
        initComponents();
        changeablemenu.setVisible(true);
        profilepanel.setVisible(true);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainsidepanel = new javax.swing.JPanel();
        allcustomerbtn = new javax.swing.JButton();
        profilebtn1 = new javax.swing.JButton();
        orederreqbtn1 = new javax.swing.JButton();
        allemployeebtn1 = new javax.swing.JButton();
        allordersbtn1 = new javax.swing.JButton();
        managepaymentbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changeablemenu = new javax.swing.JPanel();
        profilepanel = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderreqpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderreqtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        allemployeepanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        allorderspanel = new javax.swing.JPanel();
        allorderstable = new javax.swing.JScrollPane();
        allordertable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        managepaymentpanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        allcustomerspanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allcustomerstable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        addemployeepanel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        addempnametf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        addempadresstf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        addempphonetf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        addempemailtf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        addempareatf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        addempsalarytf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 850));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainsidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allcustomerbtn.setBackground(new java.awt.Color(0, 0, 0));
        allcustomerbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allcustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        allcustomerbtn.setText("ALL CUSTOMERS");
        allcustomerbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        allcustomerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allcustomerbtnMouseClicked(evt);
            }
        });
        mainsidepanel.add(allcustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 210, 50));

        profilebtn1.setBackground(new java.awt.Color(0, 0, 0));
        profilebtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profilebtn1.setForeground(new java.awt.Color(255, 255, 255));
        profilebtn1.setText("PROFILE");
        profilebtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        profilebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilebtn1MouseClicked(evt);
            }
        });
        mainsidepanel.add(profilebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 50));

        orederreqbtn1.setBackground(new java.awt.Color(0, 0, 0));
        orederreqbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orederreqbtn1.setForeground(new java.awt.Color(255, 255, 255));
        orederreqbtn1.setText("ORDER REQUEST");
        orederreqbtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        orederreqbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orederreqbtn1MouseClicked(evt);
            }
        });
        mainsidepanel.add(orederreqbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 50));

        allemployeebtn1.setBackground(new java.awt.Color(0, 0, 0));
        allemployeebtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allemployeebtn1.setForeground(new java.awt.Color(255, 255, 255));
        allemployeebtn1.setText("ALL EMPLOYEE");
        allemployeebtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        allemployeebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allemployeebtn1MouseClicked(evt);
            }
        });
        mainsidepanel.add(allemployeebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 50));

        allordersbtn1.setBackground(new java.awt.Color(0, 0, 0));
        allordersbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allordersbtn1.setForeground(new java.awt.Color(255, 255, 255));
        allordersbtn1.setText("ALL ORDERS");
        allordersbtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        allordersbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allordersbtn1MouseClicked(evt);
            }
        });
        mainsidepanel.add(allordersbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 210, 50));

        managepaymentbtn1.setBackground(new java.awt.Color(0, 0, 0));
        managepaymentbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        managepaymentbtn1.setForeground(new java.awt.Color(255, 255, 255));
        managepaymentbtn1.setText("MANGE PAYMENT");
        managepaymentbtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        managepaymentbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managepaymentbtn1MouseClicked(evt);
            }
        });
        mainsidepanel.add(managepaymentbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SidePanel.jpg"))); // NOI18N
        mainsidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -20, 410, 1020));

        getContentPane().add(mainsidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 850));

        changeablemenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilepanel.setBackground(new java.awt.Color(255, 255, 255));
        profilepanel.setMinimumSize(new java.awt.Dimension(1131, 850));
        profilepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(204, 51, 0));
        jButton13.setText("X");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        profilepanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));
        profilepanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("EMAIL:");
        profilepanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("NAME:");
        profilepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("ADMIN");
        profilepanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        profilepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1130, 850));

        changeablemenu.add(profilepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        orderreqpanel.setBackground(new java.awt.Color(255, 255, 255));
        orderreqpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderreqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUS NO", "CUS ADRESS", "DATE", "TIME", "REC NAME", "REC ADRESS", "REC PHONE", "CITY", "AREA", "STATUS", "TOTAL COST"
            }
        ));
        jScrollPane1.setViewportView(orderreqtable);

        orderreqpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 950, 650));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACCEPT ALL");
        orderreqpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 760, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText(":ORDER REQUESTS:");
        orderreqpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
        orderreqpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1050, 850));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(204, 51, 0));
        jButton12.setText("X");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        orderreqpanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        changeablemenu.add(orderreqpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        allemployeepanel.setBackground(new java.awt.Color(255, 255, 255));
        allemployeepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("SAVE CHANGES");
        allemployeepanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 730, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText(":ALL EMPLOYEE:");
        allemployeepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jButton2.setText("ADD EMPLOYEE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        allemployeepanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 730, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ADRESS", "PHONE NO", "E-MAIL", "AREA", "SALARY"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        allemployeepanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1050, 610));
        allemployeepanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1050, 850));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 51, 0));
        jButton10.setText("X");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        allemployeepanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        changeablemenu.add(allemployeepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        allorderspanel.setBackground(new java.awt.Color(255, 255, 255));
        allorderspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ORDER NO", "CUS NO", "CUS ADRESS", "DATE", "TIME", "REC NAME", "REC ADRESS", "REC PHONE", "CITY", "AREA", "STATUS", "TOTAL COST", "PAY stat"
            }
        ));
        allorderstable.setViewportView(allordertable);

        allorderspanel.add(allorderstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1050, 650));

        jButton4.setText("SAVE");
        allorderspanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 760, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText(":ALL ORDERS:");
        allorderspanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        allorderspanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1050, 860));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 51, 0));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        allorderspanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        changeablemenu.add(allorderspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        managepaymentpanel.setBackground(new java.awt.Color(255, 255, 255));
        managepaymentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("MANAGE PAYMENT");
        managepaymentpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        managepaymentpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 850));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 51, 0));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        managepaymentpanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        changeablemenu.add(managepaymentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        allcustomerspanel.setBackground(new java.awt.Color(255, 255, 255));
        allcustomerspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText(":ALL CUSTOMERS:");
        allcustomerspanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        allcustomerstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ADRESS", "PHONE NO", "E-MAIL", "AREA", "ORDERS COUNT"
            }
        ));
        jScrollPane3.setViewportView(allcustomerstable);

        allcustomerspanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1050, 610));
        allcustomerspanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1050, 860));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 51, 0));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        allcustomerspanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        changeablemenu.add(allcustomerspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        addemployeepanel.setBackground(new java.awt.Color(32, 32, 32));
        addemployeepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 51, 0));
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        addemployeepanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 33));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":ADD EMPLOYEE:");
        addemployeepanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        addemployeepanel.add(addempnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 390, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SALARY:");
        addemployeepanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, -1));
        addemployeepanel.add(addempadresstf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 390, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PHONE NO:");
        addemployeepanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));
        addemployeepanel.add(addempphonetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 390, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("E-MAIL:");
        addemployeepanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));
        addemployeepanel.add(addempemailtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 390, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("AREA:");
        addemployeepanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));
        addemployeepanel.add(addempareatf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 400, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ADRESS:");
        addemployeepanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        addemployeepanel.add(addempsalarytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 400, -1));

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ADD EMPLOYEE");
        addemployeepanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 690, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NAME:");
        addemployeepanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
        addemployeepanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1130, 860));

        changeablemenu.add(addemployeepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 850));

        getContentPane().add(changeablemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1050, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profilebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtn1MouseClicked
        changeablemenu.setVisible(true);
        profilepanel.setVisible(true);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
    }//GEN-LAST:event_profilebtn1MouseClicked

    private void orederreqbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orederreqbtn1MouseClicked
        changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(true);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
    }//GEN-LAST:event_orederreqbtn1MouseClicked

    private void allemployeebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allemployeebtn1MouseClicked
         changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(true);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
    }//GEN-LAST:event_allemployeebtn1MouseClicked

    private void allordersbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allordersbtn1MouseClicked
         changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(true);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
    }//GEN-LAST:event_allordersbtn1MouseClicked

    private void managepaymentbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepaymentbtn1MouseClicked
         changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(true);
        allcustomerspanel.setVisible(false);
    }//GEN-LAST:event_managepaymentbtn1MouseClicked

    private void allcustomerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allcustomerbtnMouseClicked
         changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(true);
    }//GEN-LAST:event_allcustomerbtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        changeablemenu.setVisible(true);
        profilepanel.setVisible(false);
        orderreqpanel.setVisible(false);
        allemployeepanel.setVisible(false);
        allorderspanel.setVisible(false);
        managepaymentpanel.setVisible(false);
        allcustomerspanel.setVisible(false);
        addemployeepanel.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addempadresstf;
    private javax.swing.JTextField addempareatf;
    private javax.swing.JTextField addempemailtf;
    private javax.swing.JPanel addemployeepanel;
    private javax.swing.JTextField addempnametf;
    private javax.swing.JTextField addempphonetf;
    private javax.swing.JTextField addempsalarytf;
    private javax.swing.JButton allcustomerbtn;
    private javax.swing.JPanel allcustomerspanel;
    private javax.swing.JTable allcustomerstable;
    private javax.swing.JButton allemployeebtn1;
    private javax.swing.JPanel allemployeepanel;
    private javax.swing.JButton allordersbtn1;
    private javax.swing.JPanel allorderspanel;
    private javax.swing.JScrollPane allorderstable;
    private javax.swing.JTable allordertable;
    private javax.swing.JPanel changeablemenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainsidepanel;
    private javax.swing.JButton managepaymentbtn1;
    private javax.swing.JPanel managepaymentpanel;
    private javax.swing.JPanel orderreqpanel;
    private javax.swing.JTable orderreqtable;
    private javax.swing.JButton orederreqbtn1;
    private javax.swing.JButton profilebtn1;
    private javax.swing.JPanel profilepanel;
    // End of variables declaration//GEN-END:variables
}
