/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import Database.ConnectDB;
import java.sql.*;

/**
 *
 *
 * @author rusla
 */
public class employeemenu extends javax.swing.JFrame {

    private Connection connection;

    /**
     * Creates new form employeemenu
     */
    public employeemenu() {
        initComponents();
        this.connection = ConnectDB.getConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        mainsidepanelemployee = new javax.swing.JPanel();
        empcompletedorderbtn = new javax.swing.JButton();
        employeeprofilebtn = new javax.swing.JButton();
        empacceptorderbtn = new javax.swing.JButton();
        emppendingorderbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changeablemenuemployee = new javax.swing.JPanel();
        employeeprofile = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        acceptorderpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        allorderstable = new javax.swing.JScrollPane();
        allordertable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pendingorderpanel = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        allorderstable1 = new javax.swing.JScrollPane();
        allordertable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        completedorder = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        allorderstable2 = new javax.swing.JScrollPane();
        allordertable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainsidepanelemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empcompletedorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        empcompletedorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empcompletedorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        empcompletedorderbtn.setText("COMPLETED ORDER");
        empcompletedorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        empcompletedorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empcompletedorderbtnMouseClicked(evt);
            }
        });
        empcompletedorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcompletedorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(empcompletedorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 230, 50));

        employeeprofilebtn.setBackground(new java.awt.Color(0, 0, 0));
        employeeprofilebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeprofilebtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeprofilebtn.setText("PROFILE");
        employeeprofilebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        employeeprofilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeprofilebtnMouseClicked(evt);
            }
        });
        employeeprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeprofilebtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(employeeprofilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 50));

        empacceptorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        empacceptorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empacceptorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        empacceptorderbtn.setText("ORDER REQUEST");
        empacceptorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        empacceptorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empacceptorderbtnMouseClicked(evt);
            }
        });
        empacceptorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empacceptorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(empacceptorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 230, 50));

        emppendingorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        emppendingorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emppendingorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        emppendingorderbtn.setText("PENDING DELIVERY");
        emppendingorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        emppendingorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emppendingorderbtnMouseClicked(evt);
            }
        });
        emppendingorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emppendingorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(emppendingorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SidePanel.jpg"))); // NOI18N
        mainsidepanelemployee.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -20, 420, 1050));

        getContentPane().add(mainsidepanelemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 850));

        changeablemenuemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeprofile.setBackground(new java.awt.Color(255, 255, 255));
        employeeprofile.setMinimumSize(new java.awt.Dimension(950, 850));
        employeeprofile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        employeeprofile.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Profile");
        employeeprofile.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/employeeicon.png"))); // NOI18N
        employeeprofile.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 190));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 51, 0));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        employeeprofile.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Name");
        employeeprofile.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Email");
        employeeprofile.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setText("Password");
        employeeprofile.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));
        employeeprofile.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 140, 30));
        employeeprofile.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 140, 30));

        jPasswordField1.setText("jPasswordField1");
        employeeprofile.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Phone");
        employeeprofile.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setText("Branch Id");
        employeeprofile.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setText("Rank");
        employeeprofile.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, -1, -1));
        employeeprofile.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 140, 30));
        employeeprofile.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 140, 30));
        employeeprofile.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 140, 30));

        jButton12.setText("Change Password");
        employeeprofile.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, -1, -1));

        changeablemenuemployee.add(employeeprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        acceptorderpanel.setBackground(new java.awt.Color(255, 255, 255));
        acceptorderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText(":ORDER REQUEST:");
        acceptorderpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        allordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EMPLOYEE ORDER ID", "CUSTOMER ID", "ORDER ID", "STATUS"
            }
        ));
        allorderstable.setViewportView(allordertable);

        acceptorderpanel.add(allorderstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 880, 260));
        acceptorderpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -340, 1010, 860));

        jButton2.setText("View Customer Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        acceptorderpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 160, -1));

        jButton3.setText("View Order Details");
        acceptorderpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        jButton4.setText("Accept Order");
        acceptorderpanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        jButton6.setText("Reject Order");
        acceptorderpanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, -1, -1));

        changeablemenuemployee.add(acceptorderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        pendingorderpanel.setBackground(new java.awt.Color(255, 255, 255));
        pendingorderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 51, 0));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pendingorderpanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        allordertable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EMPLOYEE ORDER ID", "CUSTOMER ID", "ORDER ID", "STATUS"
            }
        ));
        allorderstable1.setViewportView(allordertable1);

        pendingorderpanel.add(allorderstable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 860, 380));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText(":PENDING DELIVERY:");
        pendingorderpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        pendingorderpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 770));

        jButton5.setText("View Order Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pendingorderpanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 140, 40));

        jButton11.setText("Change Order Status");
        pendingorderpanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, 40));

        changeablemenuemployee.add(pendingorderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        completedorder.setBackground(new java.awt.Color(255, 255, 255));
        completedorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 51, 0));
        jButton10.setText("X");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        completedorder.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        allordertable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EMPLOYEE ORDER ID", "CUSTOMER ID", "ORDER ID", "STATUS"
            }
        ));
        allorderstable2.setViewportView(allordertable2);

        completedorder.add(allorderstable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 920, 410));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText(":COMPLETED ORDER:");
        completedorder.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        completedorder.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1030, 860));

        changeablemenuemployee.add(completedorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        getContentPane().add(changeablemenuemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1030, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeprofilebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeprofilebtnMouseClicked
        changeablemenuemployee.setVisible(true);
        acceptorderpanel.setVisible(false);
        employeeprofile.setVisible(true);
        completedorder.setVisible(false);
        pendingorderpanel.setVisible(false);
    }//GEN-LAST:event_employeeprofilebtnMouseClicked

    private void empacceptorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empacceptorderbtnMouseClicked
        changeablemenuemployee.setVisible(true);
        acceptorderpanel.setVisible(true);
        employeeprofile.setVisible(false);
        completedorder.setVisible(false);
        pendingorderpanel.setVisible(false);
    }//GEN-LAST:event_empacceptorderbtnMouseClicked

    private void emppendingorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emppendingorderbtnMouseClicked
        changeablemenuemployee.setVisible(true);
        acceptorderpanel.setVisible(false);
        employeeprofile.setVisible(false);
        completedorder.setVisible(false);
        pendingorderpanel.setVisible(true);
    }//GEN-LAST:event_emppendingorderbtnMouseClicked

    private void empcompletedorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empcompletedorderbtnMouseClicked
        changeablemenuemployee.setVisible(true);
        acceptorderpanel.setVisible(false);
        employeeprofile.setVisible(false);
        completedorder.setVisible(true);
        pendingorderpanel.setVisible(false);
    }//GEN-LAST:event_empcompletedorderbtnMouseClicked

    private void employeeprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeprofilebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeprofilebtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void empacceptorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empacceptorderbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empacceptorderbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Custome details:");
        String sql = "select * from CUSTOMERINFO";
        try {
            PreparedStatement ps = connection.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                System.out.println(rs.getInt("CustomerId"));
                System.out.println(rs.getString("CustomerName"));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void emppendingorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emppendingorderbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emppendingorderbtnActionPerformed

    private void empcompletedorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcompletedorderbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empcompletedorderbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeemenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acceptorderpanel;
    private javax.swing.JScrollPane allorderstable;
    private javax.swing.JScrollPane allorderstable1;
    private javax.swing.JScrollPane allorderstable2;
    private javax.swing.JTable allordertable;
    private javax.swing.JTable allordertable1;
    private javax.swing.JTable allordertable2;
    private javax.swing.JPanel changeablemenuemployee;
    private javax.swing.JPanel completedorder;
    private javax.swing.JButton empacceptorderbtn;
    private javax.swing.JButton empcompletedorderbtn;
    private javax.swing.JPanel employeeprofile;
    private javax.swing.JButton employeeprofilebtn;
    private javax.swing.JButton emppendingorderbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainsidepanelemployee;
    private javax.swing.JPanel pendingorderpanel;
    // End of variables declaration//GEN-END:variables
}
